Components/NavigationMenuViewComponent.cs
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bookstore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IBookstoreRepository repository;

        public NavigationMenuViewComponent (IBookstoreRepository r)
        {
            repository = r;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["category"];

            return View(repository.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

Controllers/HomeController.cs
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Bookstore.Models.ViewModels;

namespace Bookstore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private IBookstoreRepository _repository;

        public int PageSize = 5;

        public HomeController(ILogger<HomeController> logger, IBookstoreRepository repository)
        {
            _repository = repository;
            _logger = logger;
        }

        public IActionResult Index(string category, int page = 1)
        {
             return View(new BookListViewModel
            {
                Books = _repository.Books
                    .Where(b => category == null || b.Category == category)
                    .OrderBy(p => p.BookId)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize)
                    ,
                    PagingInfo = new Paginginfo
                    {
                        CurrentPage = page,
                        ItemsPerPage = PageSize,
                        TotalNumItems = category == null ? _repository.Books.Count() :
                            _repository.Books.Where (x => x.Category == category).Count()   
                    },
                    Type = category
            });
        }
                

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model BookListViewModel

<header>
    
</header>

<!--This is how we will populate the view page with the book information-->
@foreach (Bookstore.Models.Book x in Model.Books)
{
    <partial name="BookSummary" model="x" />
}

<div page-model="@Model.PagingInfo" page-action="index"
     page-classes-enabled="true" page-class="btn" page-class-normal="btn outline-dark"
     page-class-selected="btn-primary" page-url-category="@Model.Type"
     class="btn-group pull-right m-1">

</div>

Views/Home/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookstore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body >

        <div class="bg-transparent text-dark p-1">
            <span class="navbar-brand ml-3">Bookstore</span>
        </div>
        <div class="row m-1 p-1">
            <div class="col-3">
                <h1>Reading is adventure!</h1>
                <vc:navigation-menu />
            </div>

            <div class="col-9">
                @RenderBody()
            </div>

        </div>

        
        

</body>
</html>